### ISSUE TITLE
Inconsistent live display settings

### ISSUE THREAD

**Issue by drimulescu** [synt4x93/OTA#2]
**ACTION:** 
Set
Color profile - adaptive
Display mode - night
Color temperature - default values (6500k - day, 4800k - night)
Perform
Turn off/on the display multiple times

**Result:**
Sometimes the display mode changes from night mode value(4800k) to 6500k(cold white) and it goes back to night mode after another cycle (screen off-on)

**Expected:**
Night mode setting to be persistent during screen off/on transitions

**Comment:**
Setting both day and night values to 4800k didn't fix the issue.

**Comment by drimulescu** [comment]
![136050621_1055876858248914_7809980590404455331_n](https://user-images.githubusercontent.com/23191295/103582580-cdf8a080-4ee6-11eb-92dc-83ae29f3f214.jpg)
![136431491_431532421356603_8555741593387639577_n](https://user-images.githubusercontent.com/23191295/103582585-ce913700-4ee6-11eb-8f69-c21311a6f7bc.jpg)

**Comment by synt4x93** [comment]
Thanks for the detailed bug report, i'll look into this.

**Comment by synt4x93** [comment]
Not sure of the best way to fix this currently, but i can confirm your issue.

**Comment by drimulescu** [comment]
Hello,
Since I posted this issue I saw that you did 2 builds. Do those builds contain some updates that may change the behavior of night light ?
Thanks
