### ISSUE TITLE
2 questions

### ISSUE THREAD

**Issue by misterhsp** [synt4x93/OTA#4]
I have there man 2 questions.
Is the 18.1 rom already usable for the crownlte (Note9)?
Do I need a suitable vendor image for 18.1 or can I just install it? Currently I have 17.1 installed.

Thanks...

**Comment by synt4x93** [comment]
Sorry didn't see this, 
yep very stable in my experience, some users have over 600 hours uptime.
any stock android 10 vendor is fine, so the one you are using for 17.1 is okay.

**Comment by misterhsp** [comment]
I can't open images formatted with cryptsetup --type luks2 with your ROM on my rooted Note9. luks1 works. With 17.1 both work. Do you have an explanation for this?

thanks a lot
