### ISSUE TITLE
Heart Rate Monitor sensor

### ISSUE THREAD

**Issue by panfilovkv** [synt4x93/OTA#5]
Good day. This is what happens on my phone:  https://drive.google.com/file/d/1P7LmbGwESQE-wjXOzeoF9cYSYEA63O7d/view?usp=sharing

**Comment by synt4x93** [comment]
That's very strange, I assume you're not trying to use the sensor when this happens? If so I've never seen that before

**Comment by panfilovkv** [comment]
No application uses a sensor. I discovered this by accident when I put the phone in my backpack, and I noticed that the sensor worked from touching the wall of the backpack. This surprised me a lot.

**Comment by synt4x93** [comment]
That's very odd i'm really not sure what to suggest at all.. have never experienced this ever.. something you have installed seems to be using the sensor.
Try booting in safe mode i guess (hold finger down on the reboot icon)

**Comment by synt4x93** [comment]
Also this is the application i use when checking heartrate - https://play.google.com/store/apps/details?id=com.microcadsystems.serge.heartrateanalyzer

**Comment by panfilovkv** [comment]
Thanks, I'll try

**Comment by panfilovkv** [comment]
In safe mode, this behavior of the sensor does not appear.

**Comment by synt4x93** [comment]
Strange, that does point to something you have installed then.. When you find the application i'd be interested to know what it is so i can try it aswell haha.

**Comment by panfilovkv** [comment]
Found this application, the question is closed :) Thanks for the help. Link to the application: https://play.google.com/store/apps/details?id=ru.mts.money. The sensor is activated after pressing the "Accept" button.

**Comment by synt4x93** [comment]
Haha very strange, glad you found it though!
